[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
numReplicas = 1
maxConcurrentDeployments = 1

[deploy.envs]
NODE_ENV = "production"

[[deploy.services]]
name = "mongodb"
plan = "free"